#
# This file makes the server.
# Before making the server, the boost library must be installed. See the README for more information.
#

all: 
	g++ -g -o server src/ss_server.cpp src/networking.cpp src/Spreadsheet.cpp src/Graph.cpp src/Cell.cpp -lpthread -I /home/`whoami`/usr/include -std=c++11
