#
# Custom makefile automating compilation according to assignment.
# Written by Max Hanson, August 2019.
#

clean:
	rm -rf simulator

# this version is used for development
debug:
	gcc -g simulator.c -o simulator

# this version is used for grading
release:
	gcc -O2 simulator.c -o simulator
